In [2]:
from PreProgress.utils import process_csv
from plots.plot import plot
filename = "CrawlingStuff/CrawlResult/#除夕不放假#.csv"
data = process_csv(filename)
data

                                                   text          time
2                                                    滚   10月25日 23:59
3                            本来过年就没以前热闹好玩了，感觉好赶，你还来这一出   10月25日 23:59
4                                                    hh  10月25日 23:59
5                           神经病吗？你就真缺这么一天？除夕不放假你有病我有病？   10月25日 23:59
6                     想起来早年还有综艺叫五一七天乐，好陌生的感觉，现在哪来的七天//:  10月25日 23:59
...                                                 ...           ...
1414                                     还好我能灵活的早点回家过年   12月15日 14:52
1415  爸爸在烟熏腊鱼腊肉妈妈在擦窗户贴窗花而我但记得回家过年带上根元「灯火话团圆」新春礼盒灯笼在飘...  12月15日 14:16
1416               领导们应该是家里没有核心成员（父亲母亲）了，所以不知道陪伴家人的可贵吧   12月16日 21:37
1417                                    猫猫我啊，也想要双休和除夕放假  12月16日 12:34
1418  每当我想起来除夕要上班不放假，我对这个世界的怨气就到达了顶峰！ 坐牢可能休息时间都比我多吧我...  12月16日 00:08

[1387 rows x 2 columns]

In [9]:
from datetime import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
def process_time(time_str):
    # 将时间字符串解析为datetime对象
    current_year = datetime.now().year
    datetime_str = f"{current_year}年" + time_str
    datetime_obj = datetime.strptime(datetime_str, "%Y年%m月%d日 %H:%M")
    
    # 提取日期、小时和分钟
    year = datetime_obj.year
    month = datetime_obj.month
    day = datetime_obj.day
    hour = datetime_obj.hour
    minute = datetime_obj.minute
    
    return year,month,day, hour, minute
start_date = "2023-01-01"
end_date = "2023-10-27"
start_date = pd.to_datetime(start_date)
end_date = pd.to_datetime(end_date)
data[["year","month","day", "hour", "minute"]] = data["time"].apply(lambda x: pd.Series(process_time(x)))
review_num_to_hour = data.groupby(['year','month','day',"hour"])['text'].count()
review_num_to_hour = review_num_to_hour.reset_index()
print(review_num_to_hour)
review_num_to_hour['date'] = pd.to_datetime(review_num_to_hour[["year","month","day","hour"]])
review_num_to_hour = review_num_to_hour.drop(['year','month','day',"hour"], axis=1).set_index('date')
review_num_to_hour = review_num_to_hour.loc[(review_num_to_hour.index >= start_date) & (review_num_to_hour.index <= end_date)]
review_num_to_hour

     year  month  day  hour  text
0    2023     10   25    23   445
1    2023     10   26    11    42
2    2023     10   26    12    76
3    2023     10   26    13    75
4    2023     10   26    14    51
..    ...    ...  ...   ...   ...
328  2023     12   15    17     1
329  2023     12   15    19     1
330  2023     12   16     0     1
331  2023     12   16    12     1
332  2023     12   16    21     1

[333 rows x 5 columns]

                     text
date
2023-10-25 23:00:00   445
2023-10-26 11:00:00    42
2023-10-26 12:00:00    76
2023-10-26 13:00:00    75
2023-10-26 14:00:00    51
2023-10-26 15:00:00    59
2023-10-26 16:00:00    36
2023-10-26 17:00:00    12
2023-10-26 18:00:00     9
2023-10-26 19:00:00    33
2023-10-26 20:00:00     7
2023-10-26 21:00:00     4
2023-10-26 22:00:00     7
2023-10-26 23:00:00     2
2023-10-27 00:00:00     4